In [1]:
import numpy as np

X_train = np.load("../data/processed/X_train.npy")
X_test = np.load("../data/processed/X_test.npy")
y_train = np.load("../data/processed/y_train.npy")
y_test = np.load("../data/processed/y_test.npy")

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (81412, 2273)
X_test: (20354, 2273)
y_train: (81412,)
y_test: (20354,)


In [2]:
print("Training target distribution:")
print(np.bincount(y_train))

print("\nTesting target distribution:")
print(np.bincount(y_test))


Training target distribution:
[72326  9086]

Testing target distribution:
[18083  2271]


In [3]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

print("Model created successfully!")

Model created successfully!


In [4]:
model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!


In [5]:
y_pred = model.predict(X_test)

print("Predictions completed!")
print("First 20 predictions:")
print(y_pred[:20])

Predictions completed!
First 20 predictions:
[1 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1]


In [6]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)

Accuracy : 0.644787265402378
Precision: 0.16633023819136053
Recall   : 0.5442536327608983
F1-Score : 0.25479282622139765


In [7]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[11888  6195]
 [ 1035  1236]]


In [8]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:, 1]

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", roc_auc)

ROC-AUC: 0.6422751268290672


In [1]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Random Forest model created successfully!")

Random Forest model created successfully!


In [2]:
rf_model.fit(X_train, y_train)

print("Random Forest training completed!")

NameError: name 'X_train' is not defined

In [3]:
import numpy as np

X_train = np.load("../data/processed/X_train.npy")
X_test = np.load("../data/processed/X_test.npy")
y_train = np.load("../data/processed/y_train.npy")
y_test = np.load("../data/processed/y_test.npy")

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (81412, 2273)
X_test: (20354, 2273)
y_train: (81412,)
y_test: (20354,)


In [4]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Random Forest model created successfully!")

Random Forest model created successfully!


In [5]:
rf_model.fit(X_train, y_train)

print("Random Forest training completed!")

Random Forest training completed!


In [6]:
y_pred_rf = rf_model.predict(X_test)

print("Random Forest predictions completed!")
print("First 20 predictions:")
print(y_pred_rf[:20])

Random Forest predictions completed!
First 20 predictions:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print("Random Forest Results")
print("Accuracy :", accuracy_rf)
print("Precision:", precision_rf)
print("Recall   :", recall_rf)
print("F1-Score :", f1_rf)

Random Forest Results
Accuracy : 0.8878353149258131
Precision: 0.470873786407767
Recall   : 0.04271246147071774
F1-Score : 0.0783205490512717


In [8]:
from sklearn.metrics import confusion_matrix

cm_rf = confusion_matrix(y_test, y_pred_rf)

print(cm_rf)

[[17974   109]
 [ 2174    97]]


In [9]:
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("First 20 probabilities:")
print(y_prob_rf[:20])

First 20 probabilities:
[0.33 0.13 0.22 0.25 0.2  0.12 0.18 0.14 0.28 0.31 0.11 0.33 0.19 0.13
 0.2  0.15 0.11 0.11 0.07 0.27]


In [10]:
threshold = 0.30

y_pred_rf_30 = (y_prob_rf >= threshold).astype(int)

print("Predictions with threshold 0.30:")
print(y_pred_rf_30[:20])

Predictions with threshold 0.30:
[1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0]


In [11]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_rf_30 = accuracy_score(y_test, y_pred_rf_30)
precision_rf_30 = precision_score(y_test, y_pred_rf_30)
recall_rf_30 = recall_score(y_test, y_pred_rf_30)
f1_rf_30 = f1_score(y_test, y_pred_rf_30)

print("Random Forest (Threshold 0.30)")
print("Accuracy :", accuracy_rf_30)
print("Precision:", precision_rf_30)
print("Recall   :", recall_rf_30)
print("F1-Score :", f1_rf_30)

Random Forest (Threshold 0.30)
Accuracy : 0.7786184533752579
Precision: 0.2049115394771587
Recall   : 0.34169969176574194
F1-Score : 0.2561901617695609


In [12]:
import numpy as np
from sklearn.metrics import f1_score

thresholds = np.arange(0.10, 0.51, 0.05)

for threshold in thresholds:
    y_pred_temp = (y_prob_rf >= threshold).astype(int)
    f1 = f1_score(y_test, y_pred_temp)
    recall = recall_score(y_test, y_pred_temp)

    print(
        f"Threshold: {threshold:.2f} | "
        f"F1: {f1:.4f} | "
        f"Recall: {recall:.4f}"
    )

Threshold: 0.10 | F1: 0.2123 | Recall: 0.9639
Threshold: 0.15 | F1: 0.2340 | Recall: 0.8380
Threshold: 0.20 | F1: 0.2545 | Recall: 0.6671
Threshold: 0.25 | F1: 0.2617 | Recall: 0.4751
Threshold: 0.30 | F1: 0.2509 | Recall: 0.3100
Threshold: 0.35 | F1: 0.2158 | Recall: 0.1889
Threshold: 0.40 | F1: 0.1631 | Recall: 0.1123
Threshold: 0.45 | F1: 0.1128 | Recall: 0.0669
Threshold: 0.50 | F1: 0.0783 | Recall: 0.0427


In [13]:
best_threshold = 0.25

y_pred_rf_best = (y_prob_rf >= best_threshold).astype(int)

print("Final Random Forest threshold:", best_threshold)
print("Final predictions created!")

Final Random Forest threshold: 0.25
Final predictions created!


In [14]:
from sklearn.metrics import confusion_matrix

cm_rf_best = confusion_matrix(y_test, y_pred_rf_best)

print("Final Random Forest Confusion Matrix:")
print(cm_rf_best)

Final Random Forest Confusion Matrix:
[[12628  5455]
 [ 1109  1162]]


In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Final Random Forest @ 0.25")
print("Accuracy :", accuracy_score(y_test, y_pred_rf_best))
print("Precision:", precision_score(y_test, y_pred_rf_best))
print("Recall   :", recall_score(y_test, y_pred_rf_best))
print("F1-Score :", f1_score(y_test, y_pred_rf_best))

Final Random Forest @ 0.25
Accuracy : 0.67750810651469
Precision: 0.17560828169865497
Recall   : 0.5116688683399383
F1-Score : 0.26147614761476146


In [16]:
from sklearn.metrics import roc_auc_score

roc_auc_rf = roc_auc_score(y_test, y_prob_rf)

print("Random Forest ROC-AUC:", roc_auc_rf)

Random Forest ROC-AUC: 0.6523614884767491


In [1]:
import pandas as pd

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="importance",
    ascending=False
)

print(feature_importance.head(10))

NameError: name 'feature_names' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("../data/cleaned/cleaned_diabetic_data.csv")

print("Dataset loaded!")
print("Shape:", df.shape)

FileNotFoundError: [Errno 2] No such file or directory: '../data/cleaned/cleaned_diabetic_data.csv'

In [3]:
import os

print(os.listdir("../data"))

['diabetic_data.csv', 'diabetic_data_cleaned.csv', 'IDS_mapping.csv', 'processed']


In [4]:
import pandas as pd

df = pd.read_csv("../data/diabetic_data_cleaned.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

C:\Users\rgukt\AppData\Local\Temp\ipykernel_6060\2794401719.py:3: DtypeWarning: Columns (0: payer_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/diabetic_data_cleaned.csv")


Dataset loaded successfully!
Shape: (101766, 50)


In [5]:
df["readmitted_30"] = (df["readmitted"] == "<30").astype(int)

X = df.drop(columns=["readmitted", "readmitted_30"])

print("X shape:", X.shape)

X shape: (101766, 49)


In [6]:
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numerical_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical columns:", len(categorical_cols))
print("Numerical columns:", len(numerical_cols))

Categorical columns: 36
Numerical columns: 13


C:\Users\rgukt\AppData\Local\Temp\ipykernel_6060\1062643930.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
